class Character {
  String? name;
  String status;
  String origin;
  String height;
  String weight;
  String eyes;
  String gender;
  String species;
  String age;
  // List<String> occupation;
  String occupation;
  String biography;
  String imageAsset;

  Character(
      {this.name,
      required this.status,
      required this.origin,
      required this.height,
      required this.weight,
      required this.eyes,
      required this.gender,
      required this.species,
      required this.age,
      required this.occupation,
      required this.biography,
      required this.imageAsset});
}

var characterlist = [
  Character(
      name: "Akuma",
      status: "Alive",
      origin: "Japan",
      height: "178",
      weight: "90",
      eyes: "Red",
      gender: "Male",
      species: "Human/Demon",
      age: "Unknown",
      occupation: "Martial Artist",
      biography:
          "A mysterious individual whose origins remain still murky, in the Street Fighter universe, Akuma originally was one of two students who trained to be the heir of a powerful yet obscure Ansatsuken martial arts in Japan. Akuma and his older brother, Gouken, learned under their master Goutetsu. Goutetsu soon began to teach them the more brutal secrets behind their martial art and revealed the central aspect responsible for their style to be known as a killing art. As Gouken left amicably to found his own branch of the school that did not rely on drawing upon its darker and potentially lethal aspects, Akuma continued on to inherit the school's killing tradition, Satsui no Hadō. Much unlike his master, who embraced its lethal aspects to a controllable degree and without giving in to its darkness, Akuma took the malevolent aspects further and cast off his humanity to fully realize the true strength of his style. To truly inherit the school, Akuma challenged Goutetsu to a duel to the death and defeated his master in battle. Goutetsu died happy that his student had surpassed him. Akuma took Goutetsu's prayer beads after he defeated him, and still wears them now. Unknown to him, Gouken was on his way to see Goutetsu after years of separation, but found only his master's dead body. Since then, Gouken and Akuma parted ways as enemies and would come to fiercely clash over the direction of their martial arts' disposition well into the future.",
      imageAsset: "images/akuma.jpg"),
  Character(
      name: "Alisa",
      status: "Alive",
      origin: "Russia",
      height: "172",
      weight: "70",
      eyes: "Green",
      gender: "Female",
      species: "Android",
      age: "Unknown",
      occupation: "Protector of Jin Kazama",
      biography:
          "Doctor Bosconovitch, a genius Russian scientist, had long been seeking a way to revive his daughter. Alisa is the fruit of that research, being a robot who bears her image, name, and personality. Alisa was created by Doctor Bosconovitch, and, according to her Tekken 6 prologue, nothing else is known about her past history. Aside from her creator, only a few people know about her being a robot; among them are Jin Kazama, Wang Jinrei, Raven, Lars Alexandersson, Nina Williams, and Lee Chaolan. Alisa was created in a secret research laboratory of the Mishima Zaibatsu, deep in a forest, overseen by a secret service directly under Jin Kazama's control. She was designed to answer directly to Jin, and her autonomy can be overridden by a command from him (later she is reprogrammed by Lee Chaolan so that this can no longer occur). Neither Nina, Eddy, or the rest of Tekken Force were aware of the project to build Alisa. It is implied that Alisa had been awake prior to the events of Tekken 6, as she related conversations she has had with Doctor Bosconovitch in the past.[4] The lab Alisa was built in, Bosconovitch Laboratory, specialized in creating high-tech weaponry for the Mishima Zaibatsu",
      imageAsset: "images/alisa.jpg"),
  Character(
      name: "Anna William",
      status: "Alive",
      origin: "Ireland",
      height: "163",
      weight: "49",
      eyes: "Blue",
      gender: "Female",
      species: "Human",
      age: "41",
      occupation: "Assassin",
      biography:
          "Anna comes from a family of assassins. Although just as skilled and deadly as Nina, she has a personality that greatly contrasts her sister's. Anna holds a less serious personality, appearing markedly more playful, flirtatious and more sociable than Nina who, in turn, is reclusive, brooding and cold-hearted. Anna has a vindictive sibling rivalry with her older sister, that goes back many years. This rivalry seems to have stemmed from their relationship with their father, Richard Williams, whom Anna believes favored Nina over her. Nina is a more merciless character who will go to any lengths for victory, whilst Anna is shown to have reservations over their rivalry and sometimes even affection for Nina. Anna thus is shown losing to Nina in almost all of her endings except Tekken Tag Tournament 2. One of the reasons Anna chose to go into cryosleep was because she did not wish to live in a world without Nina (the other reason was she was worried Nina might wake up more beautiful and young-looking than her). When Nina awoke from cryosleep without her memories, Anna harbored hopes of being able to start over with her, implying that her rivalry with Nina has always stemmed from a desire to be accepted by her and to be on good terms with her, something that Nina never had any interest in before. From Tekken 5 onward, Anna continues to act in a similar flirtatious manner as she did in her former appearances, but appears more dominant and taunting towards her foes, sometimes sitting on them and laughing at their expense or even striking sensual poses or blowing kisses upon victory, being the epitome of the classic femme fatale. In Tekken 6 Anna returned to the employment of her former boss, Kazuya Mishima, now head of G Corporation, and she sought to compete across from Nina who had taken on a high position in Jin Kazama's Mishima Zaibatsu. At some point during her employment however, Anna fell in love with a G Corp captain, and decided to retire both from G Corporation and from the sibling rivalry that had dominated her life. Anna is absent from the main Tekken 7 story, having retired from G Corporation. After Nina left Heihachi Mishima's employ however, she took on independent assassination missions, one of which involved a hit on a man with Mafia connections. The target was Anna's fiancé, whom Nina killed on Anna's wedding day, stealing her wedding dress to do so. With all hope of retirement gone and higher stakes to their hatred, it seems unlikely that Anna will be able to forgive her sister again. She begins her fight with Nina by saying ill tear you to pieces, Nina!",
      imageAsset: "images/anna.jpg"),
  Character(
      name: "Asuka Kazama",
      status: "Alive",
      origin: "Japan",
      height: "165",
      weight: "54",
      eyes: "Brown",
      gender: "Female",
      species: "Human",
      age: "17",
      occupation: "Student",
      biography:
          "Asuka has a tomboyish personality and is quite brash and arrogant. Although her profile states that she breaks up fights regularly, she seems to have no qualms about fighting and seemingly revels in it. In her story mode, after defeating her target, Feng Wei, she decides to remain in the tournament in order to have fun. Her pre and post-match quotes also demonstrate her confidence. As stated in her Tekken 5 / Dark Resurrection prologue, Asuka is also known as being a nosy kid who likes to solve other people's problems, usually by knockout. According to her Tag 2 ending, she often goes around looking for gang fights to stop in Shinsekai, which is known as Osaka's most dangerous neighborhood. Asuka speaks in Kansai dialect (Kansai is a region of western Japan encompassing major cities such as Kyoto, Osaka, and Kobe). Asuka is somehow related to Jun Kazama (Jin's mother) and is the rival of Emilie Lili De Rochefort.",
      imageAsset: "images/asuka.jpg"),
  Character(
      name: "Armor King",
      status: "Alive",
      origin: "Unknown",
      height: "180",
      weight: "78",
      eyes: "Heterochromatic",
      gender: "Male",
      species: "Human",
      age: "Unknown",
      occupation: "Pro Wrestler",
      biography:
          "Armor King II's past is shrouded in mystery. What is known is that he and his older brother were a wrestling tag team, both using the same outfit and name. Why his brother decided to keep this a secret from King II while he was training him to be the successor of the original King is unknown. After the third King of Iron Fist Tournament, the original Armor King was attacked and killed by Craig Marduk in a bar brawl in Arizona, leading Armor King to develop an intense hatred for Marduk. King II enters a fourth tournament to avenge his mentor, but when he chooses to forgive and befriend the killer, an enraged Armor King II enters the fifth tournament to seek revenge himself; he faces Marduk in the tournament and is successful in defeating him. Defeating Marduk in the fifth tournament, however, was not enough to satisfy Armor King II; after the tournaments conclusion, he attacks Marduk again before disappearing. This led the duo of King II and Marduk to enter the sixth tournament in the hopes of confronting the mysterious fighter and finding his true identity, while King II also hopes to end the feud and make peace. They do make contact, but while it is revealed to King II and Marduk by Armor King II that he is the brother of the original Armor King, he reveals no further details and vows that he will never forgive Marduk. King II remained determined to put the issue to rest, but when Armor King II and Marduk next meet, another fight erupts. Armor King II refuses to forgive, and Marduk loses his patience, believing Armor King II will never be willing to listen to any explanations of Armor King's death. The confrontation is a violent one, and both Armor King II and Marduk are seriously injured and confined to hospital, leaving King II to enter the seventh King of Iron Fist Tournament alone. At the present time, both Armor King II and Marduk are recovered from their wounds and preparing themselves for a rematch.",
      imageAsset: "images/armor king.jpg"),
  Character(
      name: "Bob",
      status: "Alive",
      origin: "United State of America",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Blue",
      gender: "Male",
      species: "Human",
      age: "27",
      occupation: "Costumed Vigilante",
      biography:
          "Bob is portrayed as likable and charismatic with a strong sense of justice, usually using his fighting skills to help those in need. He is also quite cocky, appearing as a smooth talker and a bit of a ladies man. As Bob is fully confident in his abilities with his current figure, he is ironically far more insecure about losing weight than gaining it and his demeanor becomes far less enthusiastic when subject to weight loss.",
      imageAsset: "images/bob.jpg"),
  Character(
      name: "Bryan Fury",
      status: "Alive",
      origin: "United State of America",
      height: "186",
      weight: "80",
      eyes: "80",
      gender: "Male",
      species: "Cyborg",
      age: "Unknown",
      occupation: "Brain data collector",
      biography:
          "Bryan was a soldier in the US Army, who transferred to the Interpol Division of the Hong Kong Police Force. He was a skilled detective, though always followed by dark rumors. Whilst investigating the drug trade, fellow Hong Kong Interpol detective Lei Wulong discovered that Bryan had connections with drug dealers. Bryan was killed in a shoot-out in Hong Kong, possibly by Lei. Bryan corpse was transported to a laboratory belonging to Doctor Abel, a doctor willing to do anything to rival the creations of the genius scientist, Doctor Bosconovitch. Doctor Abel brought Bryan back to life through the use of cybernetic enhancements. To perfect him as a prototype for a cyborg army, Dr. Abel sent him off to steal data from Dr Bosconovitch that would complete him. Bryan originally entered the third King of Iron Fist Tournament under these auspices, and targeted Yoshimitsu, a known acquaintance of Dr Bosconovitch, in order to try and find the data he needed. Bryan appears to have been unable to get the data he needed from Yoshimitsu or Dr Bosconovitch, and subsequently realized that his life was coming to an end. On returning to Dr Abel, Bryan realized Abel had abandoned him, and had taken up working for the Mishima Zaibatsu as its top scientific advisor. Dr Abel no longer cared about what became of his obsolete cyborg creation. Bryan despised both Dr Abel for abandoning him, and Heihachi Mishima for taking Dr Abel away from him. He entered the fourth Iron Fist Tournament in order to take control of the Mishima Zaibatsu and get Dr Abel to modify his body and prolong his life. Bryans plans did not go as hoped and he ended up attempting to raid the Mishima Zaibatsu by force. He was discovered injured in the Mishima Zaibatsu's vault by Yoshimitsu, who helped him escape.[10] Bryan awoke in Dr Bosconovitch's lab, where the doctor informed him he could upgrade his body. Bryan entrusted himself to the doctor, but, on awaking, realized his body was the same as before. Doctor Bosconovitch explained he needed more time to fully understand Bryan's body, but that in the mean time he was able to fit him with a perpetual power generator as an emergency measure, that would extend his life. Bryan lashed out and attacked the doctor and killed the Manji Clan members standing guard in the lab. Yoshimitsu had sworn vengeance on Bryan for attacking his rescuers, and prevented Bryan from getting far in his attempts to test the power of his generator in the fifth tournament. Enraged, Bryan began joining different battlefields, something that wasn't in short supply now that Jin Kazama had succeeded as head of the Zaibatsu, and was now waging global warfare. At this time, Bryan ended up holed up in an abandoned mansion, an ex-G Corporation testing facility, with a host of escaped G-Corp human experiments. He claims he was using the position in order to bait in strong opponents to test himself against. Eventually boring of this, when Jin announced the 6th tournament, Bryan joined it, seeking a fight that would sate his appetite. The cancellation on the 6th tournament sent Bryan back into warzones, where he went on indiscriminate rampages.[12] He ended up in a conflict zone in the USA, where a man named Bob confronted him in an effort to stop his trail of destruction.[13]",
      imageAsset: "images/bryan.jpg"),
  Character(
      name: "Claudio",
      status: "Alive",
      origin: "Italy",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Dark Blue",
      gender: "Male",
      species: "Human",
      age: "Unknown",
      occupation: "Leader of the Archers of Sirius",
      biography:
          "Claudio is somewhat sarcastic and cocky, as suggested by his intro quotes that see him calling his opponents either amateurs or an easy win, all while flicking his hair. A number of his poses and entrances have dramatic flair to them, suggesting some pride and vanity to him. One of his victory poses suggests that he can be more empathetic and kind, as he lends a hand to his opponent after they lose against him. However, in another instance, he is also shown to slow clap sarcastically. In both his and Ling Xiaoyu's ending, Claudio shows a sinister side towards his main targets, particularly Devil Gene users such as Jin Kazama, and a willingness to manipulate Xiaoyu's innocent care for Jin in order to achieve his own goals. In the non-canonical Tekken Pachislot 4, Claudio can be seen getting irate and short-tempered when exorcisms do not go well, as compared to a more gentle and compassionate appearance he has when things go his way.",
      imageAsset: "images/claudio.jpg"),
  Character(
      name: "Devil Jin",
      status: "Alive",
      origin: "Unknown",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Glowing Silver",
      gender: "Male",
      species: "Demon",
      age: "Infinite",
      occupation: "The Devil Gene",
      biography:
          "When the Devil Gene completely takes over Jin's mind, he becomes a crazed, aggressive, destructive and brooding devil. It is also evident from his dialogue in the Scenario Campaign that he does not completely share the same memories as Jin but will still retain certain sensations from time-to-time. More accurately, Devil Jin can be treated more like the Devil Gene itself within Jin's body, with Devil Jin looking down on his host as someone weak-willed and insignificant. Devil Jin seeks to acquire ultimate power, and will do whatever it takes to achieve it. He is also very confrontational and sadistic, as he has a habit of laughing at the suffering of his foes during his win animations. He refers to his opponents as prey and a numerous points in Tekken 6, he expresses a desire to eat his opponents. He relishes in the fear of those who encounter him, but this also leads him to have great disdain for non-organic beings and animals, seeing them as a bore. He does not seem to recognize Jin's friends or associates, though he does feel severe head pain when drawing close to people Jin is close to (Xiaoyu and Hwoarang) and when drawing close to Jin's relative, Asuka Kazama, who may have a devil-repelling power inherited from her family. After Hwoarang saves him from United Nations forces in Tekken 7, Devil Jin exclusively focusses on attacking the UN and not Hwoarang, though this may just be because they are the most imminent threat. Devil Jin is shown in a similar dilemma with Xiaoyu in the (likely non-canon) Tekken Pachislot 4, where he remembers her and refrains from attacking her. The only people that seem to be able to bring Jin back to his human senses, are his mother, Jun Kazama, who's spirit or a vision of her, calmed him in Tekken 4, or (non-canonically) his relative, Asuka Kazama (even though she's unaware of this power) as the Kazama family can somehow neutralize the devil gene.",
      imageAsset: "images/devil jin.jpg"),
  Character(
      name: "Dragunov",
      status: "Alive",
      origin: "Russia",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "26",
      occupation: "Spetnaz",
      biography:
          "Dragunov is cold, calculating, and totally impassive when fighting opponents. Aside from a few lines of dialogue, Dragunov is an elective mute, barely uttering a single word throughout the entire series. This tends to either annoy, confuse or unsettle other characters. He serves his motherland with utmost diligence and loyally follows orders when given. He also enjoys singing as a hobby as seen in one of his win animations where he was humming after defeating his opponent. Despite not being necessarily evil, Dragunov is very stoic and unreadable. He shows little interest in socializing with others and only focuses on the mission at hand. He shows no mercy towards his enemies or opponents and if provoked enough, will kill them if they are jeopardizing the mission. Because of these qualities, even his allies tend to be intimidated by his presence.",
      imageAsset: "images/dragunov.jpg"),
  Character(
      name: "Eddy",
      status: "Alive",
      origin: "Brazil",
      height: "188",
      weight: "75",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "29",
      occupation: "Orpanage",
      biography:
          "Eddy is a Brazilian man with dreadlocks styled in a ponytail. Some of his dreadlocks are blond on the tips. He wears an eyebrow piercing as well as rings and an earring. In the vast majority of games, Eddy's outfit uses the colors of the flag of Brazil, his country of origin.",
      imageAsset: "images/eddy.jpg"),
  Character(
      name: "Eliza",
      status: "Alive/Undead",
      origin: "Unknown",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Dark Red",
      gender: "Female",
      species: "Undead",
      age: "1000+",
      occupation: "Unknown",
      biography:
          "Eliza is a female vampire who holds the power of immortality. She claims to be 1000 years (and 4 months) old. With the intention of taking a nap, she climbed into a coffin but inadvertently slept for 600 years. Even when she is awake, she is unable to control her sleep patterns and will suddenly fall asleep at any time. Eliza was imprisoned under the De Rochefort Family estate many centuries ago by members of the Archers of Sirius, and she thus has much disdain for the group.",
      imageAsset: "images/eliza.jpg"),
  Character(
      name: "Fahkumram",
      status: "Alive",
      origin: "Thailand",
      height: "Over 200cm",
      weight: "90",
      eyes: "Black",
      gender: "Male",
      species: "Human",
      age: "28",
      occupation: "Boxer",
      biography:
          "Fahkumram is a tall, intimidating man who possesses numerous tattoos and an incredibly broad muscular appearance. His overall appearance is that of a typical Muay Thai fighter, with bands wrapped over his arms and shins and sporting Muay Thai trunks. He also possesses traditional Muay Thai 'Pra Jiad' armbands on both arms.",
      imageAsset: "images/fahkumram.jpg"),
  Character(
      name: "Feng",
      status: "Alive",
      origin: "China",
      height: "174",
      weight: "80",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "26",
      occupation: "Chinese Master of Martial Arts",
      biography:
          "A ruthless and merciless martial artist. Feng has a lust for power and fighting, which can be seen as both a strength and weakness, as while he was skilled enough to be the best in his class, his greatest flaw is that his addiction and impulsive urge to start fighting eventually got the better of him, causing him to murder his master after he scolded him for fighting outside the dojo. He seeks to become the strongest fighter in the world, and is not afraid to show his full power against any opponent that gets in his way, and has destroyed many dojos and hurt many innocents in his wake to obtain what he desires. He also seems to loathe weak people, as he says to Asuka, 'the weak don't deserve to live', when responding to why he attacked her father",
      imageAsset: "images/feng.jpg"),
  Character(
      name: "Ganryu",
      status: "Alive",
      origin: "Japan",
      height: "189",
      weight: "129",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "55",
      occupation: "Live Streamer",
      biography:
          "Ganryu was a talented rikishi whose strength and talent in the ring allowed him to become the youngest fighter ever to reach the rank of ōzeki. While having the talent to easily reach the rank of yokozuna, it was Ganryu's lifestyle outside of the ring that was to be his downfall, as his arrogant attitude and illicit gambling habit led to him being dishonorably discharged from the sport. Still determined to prove himself to be the strongest fighter in the world, Ganryu entered a new tournament to prove his strength - the King of Iron Fist Tournament.",
      imageAsset: "images/ganryu.jpg"),
  Character(
      name: "Geese Howard",
      status: "Alive",
      origin: "United State of America",
      height: "183",
      weight: "82",
      eyes: "Blue",
      gender: "Male",
      species: "Human",
      age: "43",
      occupation: "CEO of Howard Connection",
      biography:
          "Although defined by his pride and insatiable lust for power in all its forms, Geese is both cunning and strong. He knows all of the faces of power, from money to immortality, and in many cases, he is well aware of the paths by which to obtain such power; such paths were taught through the harsh lessons Geese learned during childhood and while working his way up the underworld of his native South Town. ",
      imageAsset: "images/geese.jpg"),
  Character(
      name: "Gigas",
      status: "Alive",
      origin: "Data Deleted/Unknown",
      height: "180",
      weight: "More than 100kg",
      eyes: "Orange",
      gender: "Male",
      species: "Genetically enhanced human",
      age: "N/A",
      occupation: "Bioweapon",
      biography:
          "Gigas was revealed to be the adoptive father of Katarina Alves. He adopted her from the orphanage she was sent to after the deaths of her parents. He is also the one who taught Katarina in the art of Savate before his sudden disappearance. He disappeared after he was captured by G Corporation. He was experimented on and mutated into a red hulking beast through the use of other fighter's DNA. G-Corporation intended to use him as a biotechnological weapon, and the research wing working on him considered themselves rivals to the department working on the Jack robots. He was entered into the King of the Iron Fist Tournament in order to test his fighting capabilities.",
      imageAsset: "images/gigas.jpg"),
  Character(
      name: "Heihachi Mishima",
      status: "Deceased",
      origin: "Japan",
      height: "180",
      weight: "",
      eyes: "80",
      gender: "Male",
      species: "Human",
      age: "75",
      occupation: "Reclaiming Mishima Zibatsu",
      biography:
          "Heihachi Mishima is the host of the 1st, 3rd, 4th, and 7th King of Iron Fist Tournaments. He is the final boss of Tekken 1 (if the player uses him, his final boss is his son) and Tekken 4 and the sub-boss of Tekken 3 and Tekken 7. He is the son of Jinpachi Mishima, the father of Kazuya Mishima and Lars Alexandersson, the adoptive father of Lee Chaolan, the grandfather of Jin Kazama, and the husband of Kazumi Mishima. Heihachi's fighting style is Mishima Style Fighting Karate, a style he also taught to Kazuya, Lee, and Jin. In most games, he is the CEO of the Mishima Zaibatsu, though there are periods where he loses control of the corporation to his relatives. He is also the inaugural 'Commander' of the Tekken Force Unit, establishing the private army between the 2nd and 3rd tournaments.",
      imageAsset: "images/heihachi.jpg"),
  Character(
      name: "Hwoarang",
      status: "Alive",
      origin: "South Korea",
      height: "181",
      weight: "68",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "21",
      occupation: "Leader of The Resistance",
      biography:
          "Hwoarang is a hot-headed, impulsive person who enjoys fighting. He is sometimes arrogant and brash as he likes to boast about his skills and strength. He still holds his focus on his opponents to not lose himself in his pride. He is very rebellious and does not like to obey orders, but this changes in regard to his master, Baek, whom he dearly respects. Hwoarang tends to hold a grudge towards his enemies, and he has a strong sense of determination to fight his rivals, especially Jin Kazama.",
      imageAsset: "images/hwoarang.jpg"),
  Character(
      name: "Jack-7",
      status: "Active",
      origin: "Unknown",
      height: "235",
      weight: "168",
      eyes: "Red",
      gender: "Unknown",
      species: "Cyborg",
      age: "As Long Active",
      occupation: "Weapon of Destruction",
      biography:
          "The first Jack was built by the Russian military, though with programming data provided by the Mishima Zaibatsu. It was a killing machine built purely for destruction. After proving himself in the first King of Iron Fist Tournament, updated Jack robots were put into mass production and utilized in battlegrounds. During this time, one of the Jack-2 robots came across a young girl. Suddenly developing a conscience, Jack-2 took it upon himself to look after the girl, up until the point he was destroyed by Doctor Abel. After this, Jane, the young girl rescued by Jack-2, grew up determined to restore the robot who saved her as a child. Although Jane was successful in installing Jack-2's memories into the new Gun Jack model, Gun Jack was ultimately destroyed. After this, Jane joined the G Corporation, where she continued to work on building Jack robots in the hope of restoring her beloved companion.",
      imageAsset: "images/jack7.jpg"),
  Character(
      name: "Jin Kazama",
      status: "Alive",
      origin: "Japan",
      height: "180",
      weight: "75",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "21",
      occupation: "Head of Mishima Zaibatsu",
      biography:
          "Jin Kazama is the son of Jun Kazama and Kazuya Mishima. Jun's intimate relationship with Kazuya grew and she became pregnant with Jin. Part of the devil, that fled Kazuya when he was thrown into a volcano by his father, attempted to enter Jin while he was still in his mother's womb, but Jun managed to fight it off. Afterwards, Jun moved to a remote location in the mountains on her home island of Yakushima, where she raised Jin and trained him in the Kazama family's self-defense fighting style.",
      imageAsset: "images/jin.jpg"),
  Character(
      name: "Josie",
      status: "Alive",
      origin: "Philippines",
      height: "Unknown",
      weight: 'Unknown',
      eyes: "Brown",
      gender: "Female",
      species: "Human",
      age: "Unknown",
      occupation: "Model",
      biography:
          "Josie is bright, cheerful and quite energetic, though she became prone to crying because of something that happened in her past.[2] From a young age, she was easily brought to tears and frightened by many things, and was encourage by her parents to take up martial arts to boost her confidence. Although more confident now, she still scares and cries easily, as shown in her confrontation with Kuma, where she fled in tears from him, and fainted when he tried to interrogate her. She seems to be trying to be brave however and wants to help people, as shown by her desire to join Tekken Force after seeing the typhoon relief they provided to The Philippines.",
      imageAsset: "images/josie.jpg"),
  Character(
      name: "Julia Chang",
      status: "Alive",
      origin: "United States of America",
      height: "165",
      weight: "54",
      eyes: "Brown",
      gender: "Female",
      species: "Human",
      age: "20",
      occupation: "Live Streamer",
      biography:
          "Julia's life got off to an inauspicious start; born to unknown parentage, she was abandoned as a baby in the ruins of a Native American settlement. Her fortunes changed, however, when she was found by Michelle Chang, a young woman from a native tribe who adopted her and raised her as her own. Julia grew up with a strong love for her adoptive mother and tribe, and was taught to fight so that she could protect her homeland. Julia also developed a fascination for her tribes heritage, and began studying archaeology to learn more about her forefathers.",
      imageAsset: "images/julia.jpg"),
  Character(
      name: "Katarina",
      status: "Alive",
      origin: "Brazil",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Brown",
      gender: "Female",
      species: "Human",
      age: "Unknown",
      occupation: "Unknown",
      biography:
          "Katarina is an aggressive and sassy-mouthed talker with a cocky and slightly flirtatious personality. She did however greatly respect her adoptive father, who recently disappeared and was transformed into G Corporation's brainwashed, mutated human, Gigas.",
      imageAsset: "images/katarina.jpg"),
  Character(
      name: "Kazumi Mishima",
      status: "Deceased",
      origin: "Japan",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Brown",
      gender: "Female",
      species: "Human/Demon",
      age: "Unknown",
      occupation: "Hachijo's clan Assassin",
      biography:
          "In Tekken 7: Fated Retribution during Akuma's reveal trailer, Kazumi is shown to have an antagonistic side towards her husband, as she tells Akuma he must kill him if she fails to do so. She then adds 'and also, unfortunately, my dear son, Kazuya', implying that she is also ordering Akuma to kill him.[4] In the story trailer narrated by her, her feeling towards Kazuya indicate that she primarily fears what Heihachi will do to their little son when he discovers he has her powers. A subsequent montage of destruction attributed to Heihachi also includes crimes committed by Kazuya and Jin, implying that Heihachi is responsible for setting in motion all those subsequent evils.[5] She tells Akuma that Heihachi must be killed to stop the loss of innocent life he will inevitably cause in the future. This antagonism is exacerbated in her devil form, where she becomes hostile towards her husband and sadistically mocks him for marrying her in the first place. This is due to her family's plot to kill him.",
      imageAsset: "images/kazumi.jpg"),
  Character(
      name: "Kazuya Mishima",
      status: "Alive",
      origin: "Japan",
      height: "181",
      weight: "76",
      eyes: "Black with 1 Red eye",
      gender: "Male",
      species: "Human/Demon",
      age: "41",
      occupation: "Head of G-Corp",
      biography:
          "At first glance, Kazuya seems to be another archetypal fighting game hero protagonist, supported by his clothing of choice, simple white pants and red gloves and footpads, and his justifiable quest of taking revenge on his abusive father, Heihachi Mishima. However, Kazuya was in truth intended to be more villainous from the start, as his character profile in the first Tekken stated that his reason for entering the first King of Iron Fist Tournament was to exact revenge, and then use his father's vast fortune to carry out his plans for world domination. The Russian military even learned of these plans and entered the first Jack android into the tournament to stop him. Another clue indicating Kazuya's true intent and nature was his secret costume in the Playstation port of the first game, which turned out to be Devil.",
      imageAsset: "images/kazuya.jpg"),
  Character(
      name: "King",
      status: "Alive",
      origin: "Mexico",
      height: "200",
      weight: "123",
      eyes: "Yellow",
      gender: "Male",
      species: "Human",
      age: "30",
      occupation: "",
      biography: "Manager of an Orphanage",
      imageAsset: "images/king.jpg"),
  Character(
      name: "Kuma",
      status: "Alive",
      origin: "Japan",
      height: "280",
      weight: "210",
      eyes: "Brown",
      gender: "Male",
      species: "Bear",
      age: "10",
      occupation: "Tekken Force Officer",
      biography:
          "Kuma II was first introduced in Tekken 3, and returned for all subsequent games. He replaced Kuma I, his father, who died of an old age just after the second tournament. Just like his father, the second Kuma is Heihachi Mishima's pet and bodyguard. Kuma is in love with Panda, but she neither feels the same nor has any interest in him. It is noted that although she does not love him, she does occasionally give him a thought, such as trying to tell him that she's too old for him.",
      imageAsset: "images/kuma.jpg"),
  Character(
      name: "Kunimitsu",
      status: "Alive",
      origin: "Japan",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Grey",
      gender: "Female",
      species: "Human",
      age: "Unknown",
      occupation: "Phantom Thief Kunoichi",
      biography:
          "Loyal and loving to her family, Kunimitsu dedicated herself to her shinobi training, taking up her mother's Manji Ninja Arts as the main template for her fighting style. After eventually surpassing her mother, she took up her mother's title, admiring her, and became a phantom thief, pilfering various high-stake items for high-class clients to give her family funds for a comfortable life. When her mother fell ill, she learns of the phantom sword Yoshimitsu; the legendary blade her great-grandfather desired to replicate, but could not attain as her mother was defeated by Yoshimitsu. Determined to make her mother happy, she seeks after the very sword her mother covets.",
      imageAsset: "images/kunimitsu.jpg"),
  Character(
      name: "Lars",
      status: "Alive",
      origin: "Sweden",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Blue",
      gender: "Male",
      species: "Human",
      age: "28",
      occupation: "Rebel Leader of Yggdrasil",
      biography:
          "Lars has a heroic personality and a strong sense of justice. When the Mishima Zaibatsu no longer aligned with what he believed to be right, he led a coup against them. He is clearly a man of charisma and commands the respect of his peers, as nearly half of Tekken Force chose to join his rebel army during his insurrection. He has also been shown to be short tempered as he was quick to draw a gun on his father and shoot him during Tekken 6, and became irate and furious with Jin Kazama when the latter taunted him and set his friend, Alisa Bosconovitch, against him. Lars has been shown both to have an emotional side to him - expressing anger and sorrow in Tekken 6, especially at the loss of his lieutenant, Tougou, but also to have the ability to set aside his personal feelings in order to do what is practical and necessary. In Tekken 7, he easily sets aside his previous alliance with Raven in order to recover Jin for his owns ends, and also sets aside his dislike of Jin, whilst persuading the Journalist to do the same, since Jin is necessary for his plans. Lars is self reliant, initially treating others with suspicion, as when Lee Chaolan first proposed an alliance with him, but will trust and rely on those who are proven to be loyal to him, such as Tougou, Alisa, and (later) Lee. Whilst he is a strategist, he also trusts others to lead, and often used to give command of his troops to Tougou so that he himself could fight on the front line. Lars is a pragmatic soldier and unafraid to bring a gun to a fistfight if it serves his purpose.",
      imageAsset: "images/lars.jpg"),
  Character(
      name: "Marshal Law",
      status: "Alive",
      origin: "United States of America",
      height: "179 ",
      weight: "69 ",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "48",
      occupation: "Dishwasher",
      biography:
          "Marshall always wanted to teach in his own dojo, so when he heard the announcement of the King of the Iron Fist Tournament, he took this opportunity. Law would eventually draw against Wang Jinrei. Despite this, Marshall would eventually open his own dojo. Unfortunately, his dojo was attacked and all students were injured by a Dojang Master named Baek Doo San. Law was enraged and wanted to confront his attacker. Law entered the King of the Iron Fist Tournament 2, he would eventually face his villainous assailant and successfully defeated him.",
      imageAsset: "images/law.jpg"),
  Character(
      name: "Lee Chaolan",
      status: "Alive",
      origin: "Japan",
      height: "178",
      weight: "65",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "48",
      occupation: "CEO of Violet System",
      biography:
          "Lee’s parents died when he was a young child, and he lived thereafter on the streets as an orphan. Heihachi Mishima found Lee in the streets of a Chinese city whilst he was on a business trip. Impressed by Lee's fighting potential, Heihachi adopted him as his son and brought him back with him to Japan. However, his true intention was to give his son, Kazuya Mishima, a rival and to annoy him with the threat of another son.[5] Since Lee was old enough to impress Heihachi with his fighting skills, he was likely adopted after the key events of Kazuya’s early childhood (Heihachi taking over the Mishima Zaibatsu, imprisoning his father, Jinpachi Mishima under Hon-Maru, killing his wife, Kazumi Mishima, and throwing Kazuya off a cliff), all of which occurred when Kazuya was 5 (Lee would have been 4 years old at the time).",
      imageAsset: "images/lee.jpg"),
  Character(
      name: "Lei Wulong",
      status: "Alive",
      origin: "Hongkong",
      height: "175",
      weight: "65",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "47",
      occupation: "Police Detective",
      biography:
          "A man who lives for his job. Dedicated to the point of obsession, Lei is a law-abiding and gifted cop. He is fair-minded and affable to those around him (unless they break the law). In his Tekken 5 interludes, he is shown treating his friends (such as Wang Jinrei and Steve Fox) with compassion and respect. For his enemies however, he attains a stern and direct approach to their arrest. Although his attempts can sometimes be clumsy, Lei's intentions are always virtuous in nature.",
      imageAsset: "images/lei wulong.jpg"),
  Character(
      name: "Leo",
      status: "Alive",
      origin: "Germany",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Light Blue",
      gender: "Ambigous",
      species: "Human",
      age: "17",
      occupation: "Speleologist",
      biography:
          "Leo is described as 'cute' and 'charming' on the surface, but dangerous on the inside. Despite their father's disappearance as a child, Leo's life is described as pleasant and peaceful. However, the assassination of their mother Emma Kliesen has shown Leo to be headstrong and dedicated to fighting for justice, especially when the case was dismissed by the police. This prompted them to conduct their own investigation, demonstrating that Leo is determined in their search for justice and answers. This determination drives Leo to take risks, like sneaking into a train full of armed men from the G Corporation in their Tekken Tag Tournament 2 ending (though this may be uncanonical).",
      imageAsset: "images/leo.jpg"),
  Character(
      name: "Leroy Smith",
      status: "Alive",
      origin: "United States of America",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Grey",
      gender: "Male",
      species: "Human",
      age: "Over 50",
      occupation: "Trader",
      biography:
          "Amidst Leroy's quest, a gang lord familiar with the old days informed Leroy that it was the Mishima Zaibatsu that was behind the war that tore the city apart a half a century ago. Surprised that the mega conglomerate currently waging a war to split the world in two was also responsible for the atrocities committed so long ago, Leroy nonetheless resolved to eradicate the corporation if it truly was behind all of the evils he had seen. To carry out his quest, he decided to enter the King of Iron Fist Tournament, which was organized by the Mishima Zaibatsu itself.",
      imageAsset: "images/leroy.jpg"),
  Character(
      name: "Lili",
      status: "Alive",
      origin: "Monaco",
      height: "173",
      weight: "53",
      eyes: "Blue",
      gender: "Female",
      species: "Human",
      age: "16",
      occupation: "High School Student",
      biography:
          "Lili has all the classic characteristics of an excessively spoiled girl. The only child of a wealthy oil industrialist, Lili seems to have always had a very comfortable life. She is also very mannered in her gestures during her cutscenes. Her bourgeois side being highlighted when she announces it is time for her afternoon tea, a habit that was very widespread among the aristocracy. This habit is also shown in one of her intros in Tekken 7 where she is having tea before the fight.",
      imageAsset: "images/lili.jpg"),
  Character(
      name: "Lucky Chloe",
      status: "Alive",
      origin: "Secret",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Aqua Blue",
      gender: "Female",
      species: "Human",
      age: "Secret",
      occupation: "Dancer Idol",
      biography:
          "Lucky Chloe is revealed to be mischievous and childish, as seen in Eddy's ending where she outsmarts Eddy by giving him a childish drawing after leading him to believe it was a note revealing Kazuya's whereabouts. However, in both her own and Jack-7's endings, she shows her bratty side as she forces Eddy to practice her signature poses for live shows and blames Jack-7 for Chloe herself accidentally bumping into him. She also shows no concern after witnessing Jack-7 falling off the G Corporation tower.",
      imageAsset: "images/lucky chloe.jpg"),
  Character(
      name: "Marduk",
      status: "Alive",
      origin: "Australia",
      height: "Over than 200",
      weight: "124",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "28",
      occupation: "Pro Wrestler",
      biography:
          "Marduk is an extremely violent and short-tempered individual. He is very brash and tends to be quite unkind to others around him. He is also incredibly cocky and has a huge ego. Marduk's mannerisms are very questionable and usually border on mental instability, as he is usually seen before or after a fight screaming and acting like a vicious wild animal and breathing heavily and violently. Other actions that contribute to this is when Marduk killed the younger King's mentor Armor King in a bar brawl just because he was in a bad mood (albeit it may have been unintentional). The only people that Craig seems to actually care for are his parents, as, whilst unconscious in a hospital, King saw a family photo of Marduk's mother and father on a desk next to his bed. Although just as cocky and belligerent as before, Marduk has since become progressively more good-natured after befriending his ex-rival King II.",
      imageAsset: "images/marduk.jpg"),
  Character(
      name: "Master Raven",
      status: "Alive",
      origin: "Unknown",
      height: "165",
      weight: "50",
      eyes: "Brown",
      gender: "Female",
      species: "Human",
      age: "Unknown",
      occupation: "UN Intelligence Agent",
      biography:
          "Very little is known about Master Raven. Nevertheless, the fighter appears to have a cold attitude and seems to take her mission seriously, as she says: 'Mission accomplished' when winning a battle. Much like Raven before her, her true identity remains unknown and she uses a codename 'Master Raven' suggesting that the name 'Raven' is used as a class within the United Nations secret agent division to which they both belong.",
      imageAsset: "images/master raven.jpg"),
  Character(
      name: "Miguel",
      status: "Alive",
      origin: "Spain",
      height: "185",
      weight: "80",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "26",
      occupation: "Member of Ressistance",
      biography:
          "Despite his negative side, Miguel is shown to be capable of love, especially in the case of his sister, whom he grew to trust and treasure. However, Miguel’s extremely over-protective concern for his sister made him consider killing his future brother-in-law, though he decides against it for the sake of her happiness. But, once his sister is killed in a bombing raid by the Mishima Zaibatsu ordered by Jin Kazama, Miguel finally shows his vengeful side and rages at her killer.",
      imageAsset: "images/miguel.jpg"),
  Character(
      name: "Negan",
      status: "Alive",
      origin: "United States of America",
      height: "185",
      weight: "80",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "50",
      occupation: "Leader of the Saviors",
      biography:
          "The Walking Dead’s Negan, the charismatic leader of the Saviors, brought other communities together under his thumb with the motto “people are a resource.” One day, Negan received reports that an unknown group had taken out several of his men. Per his standard policy, he enacted a plan to capture and make an example of them. The survivors fell into Negan's carefully laid trap, but, just as he was choosing his victim to serve as an example, the group put up an intense fight and escaped. Negan worried they would disturb his new world order if he did not deal with them swiftly. Taking his barbed-wire bat Lucille - named after his beloved wife - into his hand, he set out to take care of these foolish ingrates who would challenge his authority",
      imageAsset: "images/negan.jpg"),
  Character(
      name: "Nina William",
      status: "Alive",
      origin: "Ireland ",
      height: "161",
      weight: "49",
      eyes: "Blue",
      gender: "Female",
      species: "Human",
      age: "43",
      occupation: "De Factor Leader of Mishima Zaibatsu",
      biography:
          "Nina and her younger sister are from a family of assassins, and both come from the Republic of Ireland.",
      imageAsset: "images/nina.jpg"),
  Character(
      name: "Noctis",
      status: "Alive",
      origin: "Kingdom of Lucis, Insomnia",
      height: "176",
      weight: "Unknown",
      eyes: "Blue",
      gender: "Male",
      species: "Human",
      age: "30",
      occupation: "King",
      biography:
          "Noctis is the crown prince and heir to the throne of the kingdom of Lucis",
      imageAsset: "images/noctis.jpg"),
  Character(
      name: "Paul Phoenix",
      status: "Alive",
      origin: "United States of America",
      height: "187",
      weight: "81",
      eyes: "Blue",
      gender: "Male",
      species: "Human",
      age: "48",
      occupation: "Unemployed",
      biography:
          "Paul Phoenix is a tough American fighter. Something of a drifter, Paul has no real career, instead making money by streetfighting and taking occasional work as a bouncer while he pursues his real passion - to prove himself to be the toughest fighter in the universe. Paul trains with Marshall Law, who would go on to become his good friend, and Lee Chaolan, and remains undefeated in battle, with the exception of a young fighter named Kazuya, who held him to a draw. When Paul hears the announcement of a King of Iron Fist Tournament, he enters, seeing the opportunity to face his old rival and prove himself to be the best. While Paul does indeed come face to face with Kazuya, he is unable to defeat him. In the process, Paul acquires a new rival - a bear named Kuma. Two years passed before news reached Paul of a second tournament; while he was again successful in defeating Kuma, he still was not able to prove himself to be stronger than Kazuya; this time, Paul had earned the right to face Kazuya, but traffic on the Japanese highways prevented him from reaching the venue in time, forcing him to forfeit.",
      imageAsset: "images/paul.jpg"),
  Character(
      name: "Panda",
      status: "Alive",
      origin: "China",
      height: "277 ",
      weight: "200",
      eyes: "Black",
      gender: "Female",
      species: "Panda",
      age: "9",
      occupation: "Bodyguard",
      biography:
          "Panda has shown a more sinister side, where she is shown to often reject Kuma, sometimes with physical violence. Although she seems uninterested in Kuma romantically, she does occasionally think of him.",
      imageAsset: "images/panda.jpg"),
  Character(
      name: "Shaheen",
      status: "Alive",
      origin: "Saudi Arabia",
      height: "Unknown",
      weight: "Unknown",
      eyes: "Brown",
      gender: "Male",
      species: "Human",
      age: "Unknown",
      occupation: "Millitary Guard",
      biography:
          "Shaheen has brown eyes and short dark brown hair with a mustache and pretty thick facial hair. His head is adorned with a long red and white checkered shemagh and a black agal. He also wields a scimitar around his waist. He wears an off-white military uniform with a black belt tucked into his uniform, aqua blue pants and black pointed shoes.",
      imageAsset: "images/shaheen.jpg"),
  
  Character(name: "Steve Fox",status: "Alive", origin: " United Kingdom", height: "187", weight: "75", eyes: "Blue", gender: "Male", species: "Human", age: "21", occupation: "Professional Boxer", biography: "After reclaiming the Mishima Zaibatsu from his son and witnessing the power of the Devil firsthand in the second King of Iron Fist Tournament, CEO Heihachi Mishima began his own research into the terrifying power of the Devil Gene. Trying to replicate this superhuman strength, the Mishima Zaibatsu started a genetic modification plan with the goal of replicating the effects of the gene on regular humans through the creation of a synthetic Devil Gene. Heihachi used eggs from the assassin Nina Williams, who was cryogenically frozen by Dr. Bosconovitch at the Zaibatsu at the time, in order to create babies that he used to conduct these experiments. Most of the children died during this process and ultimately the supersoldier program was considered a failure.", imageAsset: "images/steve.jpg"),
  Character(name: "Ling Xiaoyu",status: "Alive", origin: "China", height: "157", weight: "42", eyes: "Brown", gender: "Female", species: "Human", age: "18", occupation: "Panda Caretaker", biography: "Xiaoyu ran away from her parents whilst on vacation with them in Hong Kong. She stowed away on a ship that bore the Mishima Zaibatsu name, in order to demand that Heihachi Mishima build her a theme park. Heihachi discovered Xiaoyu had beaten his men who'd tried to apprehend her on board, and was so impressed by her skill and audacity that he took her on as a ward of the Mishima Zaibatsu. He trained her a personal Panda bodyguard and enrolled her in Mishima Polytechnical School, where she became friends with classmate Jin Kazama.", imageAsset: "images/xiaoyu.jpg"),
  Character(name: "Yoshimitsu",status: "Alive", origin: "Japan", height: "178", weight: "63", eyes: "Changeable", gender: "Male", species: "Cybernetic Human", age: "Unknown", occupation: "Leader of Manji Clan", biography: "Yoshimitsu's benevolence hasn't changed since the first Iron Fist Tournament. He enjoys helping people who are in need, as seen with Law and his family (Yoshimitsu's ending) in Tekken. He also became the helper of Dr. Bosconovitch prior to Bryan Fury's betrayal of the Manji Clan", imageAsset: "images/yoshimitsu.jpg"),
  Character(name: "Zafina",status: "Alive", origin: "Egypt", height: "170", weight: "58", eyes: "Brown", gender: "Female", species: "Human", age: "23", occupation: "Astrologist and Imperial Tomb Defender", biography: "Since childhood, Zafina was raised to be a protector of an imperial tomb. Several years ago, a foreign army attacked the imperial tomb. Zafina single-handedly wiped them out. Since then, the group’s guru appointed her to be its sole protector.", imageAsset: "images/zafina.jpg"),
];
